language: php
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - "/^v?[0-9\\.]+$/"
php:
- '5.6'
- '7.0'
- '7.1'
- '7.2'
- '7.3'
services:
- mysql
before_script:
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- composer install
- curl -s -o $HOME/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.33.8/nvm.sh
- source $HOME/.nvm/nvm.sh
- nvm install v10.13.0
- node --version
- npm install
- npm run build
- bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1
script:
- composer test
before_deploy:
- echo 'Making deploy packages...'
- bash ./bin/cleanup.sh
- zip -r plugin-recommender.zip ./
deploy:
  provider: releases
  skip_cleanup: true
  file: plugin-recommender.zip
  api_key:
    secure: ZDYY4BOZkf723LKRmviadGGqfyn6D+LzRp7uv78NUyMRrNm9tbXygtxY4RY8wIYWm2W3G85Q09HuTWm7xWIx3rRnl9k4T1k9Uxy5b1VZFRIvpHx4aC0ORK0N1xLKcr9dRS+F0eRtkerZaVXC4kSox4INOlchaC4Z4yalIveAhG0ec4RkrZc8HQCRcjIY36V2AhSFvjDzcUaB2+QOYQ/V8ie1fM1A0sSHXyB20MTGf0QutyhbCwbreKZXbJOUQd1z194kD0y7MqFDwLlUrS7Xw3y+JCITX6U8rbEGJYrQNi68Lsig048jnwjYeAZ11spK3tRyx0wwCk4deO9l5BICYG++NUcPK96bxXsx4y7L1ir5NNMJxUggoBkXvdQwjCRRV0D6rMMJnIZnn3yhGBtq104WofMflmuBzZEzrPC3tFqvwJTJsd5ke5bMvW5NNZMA3qnIMjTgUq5+3QGDBZpJ/gZ+dpx1TD31rWuTtcUrVlmkXo+cA6fazsplzeNRFCoEjn+UOV+N1twDZcMqSMjnAOwee0jXcVPdOY1sOLPaZmRQg0bOackxxZHvsF2Jp1z7THAPDobtuFhJSYpf9E1vvDVjqhPTKqL9lMRLeMj+18zVSRwVJSAMrvRKnv+q1sKyD92UiMvYLHOyuRVRDCD2Z5l5hkQhxafD+QYn0IRruuE=
  on:
    repo: kuno1/plugin-recommendor
    tags: true
    php: "7.0"
