language: php
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
    - master
    - "/^v?[0-9\\.]+$/"
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
services:
  - mysql
before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer install
  - curl -s -o $HOME/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.33.8/nvm.sh
  - source $HOME/.nvm/nvm.sh
  - nvm install v10.13.0
  - node --version
  - npm install
  - npm run extract
  - bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1
script:
  - composer test
before_deploy:
  - echo 'Making deploy packages...'
  - bash ./bin/cleanup.sh
  - zip -r bootstrapress.zip ./
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: cKUc0vq/eI+u4zu8GT9KE/AUyKq0koyByAoU+S8nA9kLHIMedu/pFNnp1/kGDU1L/mTJEyZr5GGW5NJTczSFEbqaVkZL5E62mtHUG1MO/w4OeBAhuVLPbpesABp1erKIo9uvU4ABDbJiFGWBbQI3m5BIwzPxKRuLY9E6PvmC8DjpnKZgCZqf7Ua1MPYMluagAXOxp+Is8rfAX5Y4sqQatL/b/ZxEzjU9yCSryf3jQDN43sFC7y1SgdKSLnwVfGC0V+goXBQLH61ZLUtkD4PqhfAs48KYJtZLjzapKL9kVS5gIWGJ2UOyo+IIOaQqTkgXyFSboqdAYx7pJycVyqLoLqaFQcmsTbDnRGL0+Vox7uHjhpzhBIayppeX5ISmoHaGQt0n0aihp/wuS6SMzr94aQTwDwvS57fYyw9M0NgrjfFWlfvUdyTXnM3Yxpn3/1iCA/mPafFCMS2BDP2gZ4fphk1pZfmYC5ayDrwPyCwZQS4huOKTPQ67096/xxVhFe5PQ5fp11rcZJXf9oqLjg2qcsJgP8l0GUEryCu07usdU9vo25QGB0/JXv3CJtReyAIFLiQubkr1w9f7UA445GmW2BicVnwckuD69YFYwUASZYgOV3ZW9O+t1ijnPxblATSsJBahRYhgG+zmwGg68XZ4/spDN4WN6DluJBz5ENhKlaw=
  file: bootstrapress.zip
  on:
    repo: kuno1/bootstrapress
    tags: true
    php: '7.0'
